<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMaster.master" AutoEventWireup="true" CodeFile="category.aspx.cs" Inherits="Admin_category" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder2" Runat="Server">
    <form id="form1" runat="server">
    <asp:DetailsView ID="DetailsView1" runat="server" Height="25px" 
    Width="385px" AutoGenerateRows="False" CellPadding="4" 
    DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" 
        AllowPaging="True" AutoGenerateDeleteButton="True" 
        AutoGenerateEditButton="True" AutoGenerateInsertButton="True" 
        DataKeyNames="category_id">
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <CommandRowStyle BackColor="#D1DDF1" Font-Bold="True" />
        <RowStyle BackColor="#EFF3FB" />
        <FieldHeaderStyle BackColor="#DEE8F5" Font-Bold="True" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <Fields>
            <asp:BoundField DataField="category_id" HeaderText="category_id" 
                SortExpression="category_id" />
            <asp:BoundField DataField="category_name" HeaderText="category_name" 
                SortExpression="category_name" />
        </Fields>
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <EditRowStyle BackColor="#2461BF" />
        <AlternatingRowStyle BackColor="White" BorderColor="#CCFFFF" 
            BorderStyle="Solid" />
    </asp:DetailsView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" 
    ConnectionString="<%$ ConnectionStrings:ConnectionString %>" 
    SelectCommand="SELECT * FROM [category_master]" 
        CancelSelectOnNullParameter="False" 
        DeleteCommand="delete from category_master where category_id=@category_id" 
        InsertCommand="insert into category_master(category_id,category_name) values(@category_id,@category_name)" 
        
        
        UpdateCommand="update category_master set category_name=@category_name where category_id=@category_id"></asp:SqlDataSource>
</form>
</asp:Content>

